-- Atomized playbook rules synthesized from the 10-blog research pass + adversarial critique

INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '제목 짓는 법', '**[문제] + [구체적 숫자] + [해결 방법]** — 우아한형제들 패턴', 1);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '제목 짓는 법', '**[X로 바꾼 Y의 순서/방식]** — 전후 대비 프레임, Toss Tech 패턴', 2);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '제목 짓는 법', '**콜론 분리: [공감형 문제 제기] : [구체적 해법/원리]** — 우아한형제들·LINE 패턴', 3);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '제목 짓는 법', '**반박형 질문/도발적 클레임 + 물음표** — 요즘IT·TechCrunch 패턴', 4);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '제목 짓는 법', '**시리즈 번호 붙이기** — 카카오 패턴, 연재 리텐션용', 5);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '첫 문장 후킹 기법', '**숫자로 스테이크 제시** (Toss Tech형): 첫 문장은 상황 설명, 두 번째 문장은 하드 넘버.', 6);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '첫 문장 후킹 기법', '**트리거 상황 나열형 (동사 없는 명사구 3연타)** — 우아한형제들형', 7);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '첫 문장 후킹 기법', '**낡은 전제 뒤집기** — The Verge형', 8);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '첫 문장 후킹 기법', '**역할·자격 먼저 밝히기** — LINE형', 9);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '글 구조 패턴', '여러 이슈를 다룰 경우 이 4단 템플릿을 이슈마다 반복 적용 (스캔 가능한 카드 단위로 만듦).', 10);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '문장 리듬 규칙', '문단 길이: 1~3문장 내외. 4문장 넘는 문단이 나오면 반드시 쪼갠다. (참고: 글자수 기준의 정량 상한을 제시하는 출처 데이터는 없다 — 40~80자는 Sky Sports의 "40~60 words"라는 영어 단어수 기준을 한국어 상황에 맞게 편집자가 임의로 환산한 추정치이며, 실측·검증된 수치가 아니다. 엄격한 기준으로 쓰지 말고 감으로 참고할 것.)', 11);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '문장 리듬 규칙', '사실/숫자를 전달하는 문장은 짧게 끊는다 (단문, 주어+서술어 위주). 그 사실을 설명하는 문장은 길게 풀어써도 된다 — "짧은 사실 문장 → 긴 설명 문장" 순서를 기본 리듬으로 삼는다.', 12);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '문장 리듬 규칙', '한 문단에는 하나의 주장/사실만 담는다. 인용문(사람 말, 코드 결과, 로그)은 별도 문단으로 독립시킨다.', 13);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '문장 리듬 규칙', '종결어미는 "~습니다/~했어요" 계열로 통일하되, 지나치게 딱딱한 개조식은 피한다. 구어체 존댓말("~하는 거예요", "~려고 해요")을 섞어 동료가 설명하듯 쓴다.', 14);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '문장 리듬 규칙', '강조하고 싶은 한 문장은 앞뒤로 빈 줄을 두고 문단 하나로 독립시켜 시각적 무게를 준다.', 15);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '스캔 가능하게 만드는 장치', '**소제목**: 매 300~500자마다 하나씩. 두 가지 방식 중 선택 — 숫자형("1단계) ~", "0x01 ~") 또는 질문형("그래서 실제로 무슨 일이 있었나?"). 하나의 글 안에서는 방식을 섞지 않는다.', 16);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '스캔 가능하게 만드는 장치', '**볼드**: 핵심 용어/코인한 표현에만 사용 (문단당 1개 이하). 볼드만 훑어도 글의 논지가 읽혀야 한다.', 17);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '스캔 가능하게 만드는 장치', '**번호 리스트**: 실제 단계/사례에만 사용. 장식용 나열에는 쓰지 않는다. 마무리 요약은 항상 번호 3개 이내로 압축.', 18);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '스캔 가능하게 만드는 장치', '**코드블록/표**: 기술 설명 문단이 5문장 이상 이어질 것 같으면 코드블록, 비교표, 스크린샷 중 하나로 끊는다.', 19);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '스캔 가능하게 만드는 장치', '**콜아웃 박스**: 반박·예외·주의사항은 본문과 분리해 인용 블록으로 뺀다.', 20);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '스캔 가능하게 만드는 장치', '**바이라인/메타정보**: 작성자 역할 한 줄(예: "OO에서 백엔드로 일하고 있습니다")을 글 상단에 배치해 신뢰도를 먼저 제공한다.', 21);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '톤 가이드', '1인칭·1인칭 복수("저는", "우리 팀은")를 기본으로 쓴다. 3인칭 보도체("~라고 밝혔다")는 금지.', 22);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '톤 가이드', '실패/시행착오를 숨기지 않는다 — "처음엔 단순하게 시작했다가 운영하면서 깨진 지점" 서술을 의도적으로 포함한다. 완벽한 성공담만 쓰지 않는다.', 23);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '톤 가이드', '확신은 형용사가 아니라 구체성(숫자, 코드, 로그)에서 나온다. "정말 놀라운 성능"이 아니라 "응답 시간이 1.2초→0.3초로 줄었다"로 쓴다.', 24);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '톤 가이드', '업계 용어(MCP, RAG, HITL 등)는 설명 없이 써도 되지만, 처음 등장할 때 볼드 처리해 스캐너가 놓치지 않게 한다.', 25);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '톤 가이드', '마케팅 카피 톤(느낌표 남발, "혁신", "게임체인저") 금지. 냉정하고 담백한 확신이 이 오디언스에는 더 설득력 있다.', 26);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '제목에 구체 명사(툴명/숫자/기술명)가 최소 1개 들어가 있는가?', 27);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '첫 문장이 정의나 일반론이 아니라 구체적 사실/숫자/장면으로 시작하는가?', 28);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '4문장 넘는 문단이 하나도 없는가?', 29);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '소제목이 300~500자마다 하나씩 있는가?', 30);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '실패했던 시도나 잘못된 가정을 최소 1군데 이상 솔직히 담았는가?', 31);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '결말에 원칙(패턴 A/B) 또는 필자소개+CTA(패턴 C)로 마무리했는가?', 32);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '코드블록/표/스크린샷이 긴 기술 설명 문단 사이에 최소 1개 이상 삽입돼 있는가?', 33);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '볼드 처리만 훑어도 글의 논지가 파악되는가?', 34);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '형용사(놀라운, 혁신적인, 강력한) 대신 숫자/사실로 주장을 뒷받침했는가?', 35);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('writing', '체크리스트 (발행 전 자가 점검)', '3인칭 보도체 문장이 하나도 없는가 (모두 1인칭/1인칭 복수)?', 36);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '타이포그래피 규칙', '**3단계 크기 체계 고정**: 헤드라인(세리프, 40~56px, font-weight 700~800) → 스탠드퍼스트/데크(산세리프, 18~20px, 그레이 400 계열, 헤드라인 바로 아래) → 본문(산세리프, 16~18px, line-height 1.7 이상). 세 단계 중 하나라도 생략 금지 — 헤드라인이 압도적으로 크고 나머지는 확실히 작아야 한다는 "3단계 크기 대비" 원칙은 TechCrunch/Wired 공통 패턴에서 가져오되, 세리프 헤드라인 자체는 이 두 매체를 따른 것이 아니라 이 스타일만의 의도적인 선택이다(두 매체 모두 헤드라인은 굵은 산세리프/그로테스크 서체를 쓰며, Wired의 세리프는 본문용이다).', 1);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '타이포그래피 규칙', '**모노스페이스는 라벨 전용**: 카테고리 킥커, 날짜, 읽는시간, 코드 인용 외에는 monospace 사용 금지. 본문에 모노스페이스를 쓰면 가독성이 떨어진다 — Woowa Brothers의 `0x00` 서브헤드처럼 "빌드 로그" 느낌을 낼 때만 예외.', 2);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '타이포그래피 규칙', '**킥커는 항상 대문자 + 작은 사이즈 + 색상 대비**: 11~13px, letter-spacing 0.08em 이상, 헤드라인 색상과 다른 톤(다크 배경 위 accent 컬러). Wired/TechCrunch처럼 모든 헤드라인 위에 100% 일관되게 배치 — 예외 없이.', 3);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '타이포그래피 규칙', '**다크 배경 대비 규칙**: 본문 텍스트는 순백(#FFFFFF) 금지, #E5E5E5~#D0D0D0 톤으로 눈부심 방지. 헤드라인만 순백 또는 accent 컬러로 최대 대비.', 4);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '타이포그래피 규칙', '**코드블록 내부 폰트는 반드시 별도 지정**: 본문 산세리프와 코드 모노스페이스가 인접할 때 x-height 차이로 리듬이 깨지지 않도록 코드블록 앞뒤 여백을 본문 줄간격의 1.5배 이상 확보.', 5);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '색상과 레이아웃', '**배경은 다크 단일톤, accent는 1개만**: 배경 #0D0D0D~#121212, 텍스트 그레이 스케일, accent 컬러(터미널 그린/앰버/시안 중 택1) 하나만 링크·킥커·CTA·hover에 사용. Wired가 red 하나로 전체 사이트를 통일하듯 accent를 절대 2개 이상 쓰지 않는다.', 6);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '색상과 레이아웃', '**카테고리 태그는 색상코드 시스템으로**: 요즘IT처럼 카테고리별(AI/인프라/프로덕트/코드리뷰 등)로 뱃지 컬러를 고정 배정하고 전체 사이트에서 절대 바꾸지 않는다 — 독자가 "이 색=이 주제"를 학습하게 한다. 단, 배경이 다크이므로 채도를 낮추고 명도만 살짝 올린 톤(예: 뮤트 그린, 뮤트 앰버)을 써서 다크 캔버스와 충돌하지 않게 한다.', 7);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '색상과 레이아웃', '**레이아웃은 카드그리드 기본, 히어로는 최상단 1개만**: 데스크톱 기준 3열 그리드, 카드 순서는 항상 [썸네일/터미널 스크린샷] → [킥커 태그] → [헤드라인] → [메타(날짜·읽는시간)]. 이 순서를 절대 흔들지 않는다 — Toss Tech 패턴. (Kakao Tech Blog는 이 순서의 근거로 인용하지 않는다: 실제로는 홈 최상단에 미션/태그라인 풀와이드 밴드 → 가치관 타일 스트립 → 3단 포스트 그리드 순서로, 콘텐츠 피드보다 브랜드 메시지를 앞세우는 구조이기 때문이다. 아래 "미션/컬처 밴드" 회피 규칙에서 실제로 지양해야 할 사례에 해당한다.)', 8);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '색상과 레이아웃', '**여백은 카드 사이 최소 24px, 섹션 사이 최소 64px**: Mashable식 밀집 그리드가 아니라 Wired식 여백을 택한다 — 필드노트 톤은 "빠른 소비"가 아니라 "정독"을 지향하므로 밀도보다 여백을 우선한다.', 9);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '색상과 레이아웃', '**홈페이지 최상단에 미션/컬처 밴드 넣지 않기**: LINE Engineering이나 Kakao Tech Blog처럼 가치관 타일/브랜드 밴드를 먼저 보여주는 방식은 개인/소규모 블로그에는 과함 — 대신 최신 포스트 1개를 큰 히어로로, 그 아래 그리드로 바로 진입.', 10);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '시선을 끄는 장치', '**히어로는 페이지당 정확히 1개**: 최신 또는 편집자 선정 포스트 하나만 풀블리드 이미지 + 대형 세리프 헤드라인 + 킥커로 처리. 2개 이상의 히어로는 위계를 무너뜨린다.', 11);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '시선을 끄는 장치', '**스탯 카드는 숫자 강조용으로만, 최대 3개 나란히**: 세리프가 아닌 모노스페이스 큰 숫자(예: `42ms`, `3.2x`) + 하단에 라벨(산세리프 소문자). 본문 중간에 데이터를 보여줄 때만 삽입, 장식용으로 남발 금지.', 12);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '시선을 끄는 장치', '**풀쿼트는 accent 컬러 좌측 보더 4px + 세리프 이탤릭**: 본문보다 1.3배 큰 사이즈, 최대 2줄. 한 아티클에 1~2개 이하로 제한 — 남발 시 위계 붕괴.', 13);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '시선을 끄는 장치', '**LIVE/업데이트 배지는 텍스트에도 중복 표기**: Sky Sports 패턴처럼 "진행중" 같은 상태는 배지(비주얼) + 헤드라인 텍스트(카피) 양쪽에 동시에 넣어 알림/링크 미리보기에서도 상태가 유실되지 않게 한다.', 14);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '시선을 끄는 장치', '**accent 컬러는 인터랙션 신호로만 예약**: 링크 hover, 활성 탭, CTA 버튼, 킥커 태그 — 이 4곳에만 쓴다. 장식적 배경색이나 아이콘 채우기에 accent를 쓰면 "클릭 가능"이라는 신호가 희석된다.', 15);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', '모든 헤드라인 위에 킥커(카테고리 라벨)가 100% 예외 없이 붙어 있는가?', 16);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', '페이지 안에 히어로 이미지+헤드라인 조합이 정확히 1개인가 (2개 이상 아닌가)?', 17);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', 'accent 컬러가 1개로 통일되어 있고 2개 이상 섞이지 않았는가?', 18);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', '카드 그리드의 요소 순서(썸네일→태그→헤드라인→메타)가 전체 페이지에서 일관되는가?', 19);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', '다크 배경 위 본문 텍스트가 순백(#FFF)이 아니라 그레이톤(#D0D0D0 내외)으로 눈부심을 피했는가?', 20);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', '카드 간 여백 24px 이상, 섹션 간 64px 이상을 지켰는가 (밀집 그리드로 몰리지 않았는가)?', 21);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', '모노스페이스가 라벨/코드 외 본문에 새어 들어가지 않았는가?', 22);
INSERT INTO wordpress_playbook_rules (category, section, rule_text, sort_order) VALUES ('design', '체크리스트', '풀쿼트/스탯카드가 아티클당 각각 2~3개 이하로 절제되어 있는가?', 23);
